In [1]:
import numpy as np

In [2]:
array1=np.arange(16)
array2=np.arange(10,40)
print(array1)
print(array2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39]


In [3]:
dim=np.ndim(array2)
shape=np.shape(array2)
dtype=array2.dtype
size=array2.size
itemsize=array2.itemsize
byte=array2.nbytes

In [4]:
print('The shape of the array2 is: ',shape)
print('The dimension of array2 is: ',dim)
print('The data type of array 2 is: ',dtype)
print('The size of array2 is: ',size)
print('The itemsize of array2 is :',itemsize)
print('The total bytes taken by array 2 is: ',byte)

The shape of the array2 is:  (30,)
The dimension of array2 is:  1
The data type of array 2 is:  int32
The size of array2 is:  30
The itemsize of array2 is : 4
The total bytes taken by array 2 is:  120


In [5]:
array1=array1.reshape(4,4)   ###CHANGING SHAPE
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
array1.diagonal()     ### ALL DIAGONALS OF ARRAY1

array([ 0,  5, 10, 15])

In [54]:
np.linalg.det(array1)

0.0

In [7]:
array1.trace()        ### SUM OF DIAGONALS OF ARRAY1

30

In [8]:
array1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]], dtype=int32)

In [9]:
np.square(array2)

array([ 100,  121,  144,  169,  196,  225,  256,  289,  324,  361,  400,
        441,  484,  529,  576,  625,  676,  729,  784,  841,  900,  961,
       1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521], dtype=int32)

In [55]:
np.sqrt(array2)

array([3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ])

In [10]:
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
##ADDING 0 ON BORDER AND 1 INSIDE array1 (deep copy)
array1[::,0]=0
array1[::,-1]=0
array1[0,::]=0
array1[-1,::]=0
array1[1,1:3]=1
array1[2,1:3]=1
array1

array([[0, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 0]])

In [12]:
array2.flatten()

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [13]:
array1.ravel()

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0])

In [14]:
np.repeat(array1,2)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.tile(array1,2)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 1, 1, 0],
       [0, 1, 1, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [16]:
array2T=array2.T
np.dot(array2T,array2)

20255

In [23]:
array3=np.arange(16,32).reshape(4,4)
np.linalg.inv(array3)

array([[ 2.90857476e+14, -2.95548726e+14, -2.81474977e+14,
         2.86166226e+14],
       [-8.91337426e+14,  1.19626865e+15,  2.81474977e+14,
        -5.86406201e+14],
       [ 9.10102425e+14, -1.50589113e+15,  2.81474977e+14,
         3.14313724e+14],
       [-3.09622474e+14,  6.05171200e+14, -2.81474977e+14,
        -1.40737488e+13]])

In [26]:
hstack=np.hstack((array1,array3))
hstack

array([[ 0,  0,  0,  0, 16, 17, 18, 19],
       [ 0,  1,  1,  0, 20, 21, 22, 23],
       [ 0,  1,  1,  0, 24, 25, 26, 27],
       [ 0,  0,  0,  0, 28, 29, 30, 31]])

In [27]:
vstack=np.vstack((array1,array3))
vstack

array([[ 0,  0,  0,  0],
       [ 0,  1,  1,  0],
       [ 0,  1,  1,  0],
       [ 0,  0,  0,  0],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [33]:
split=np.split(array3,2)
split

[array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[24, 25, 26, 27],
        [28, 29, 30, 31]])]

In [34]:
splitvertical=np.split(array1,4,axis=1)
splitvertical

[array([[0],
        [0],
        [0],
        [0]]),
 array([[0],
        [1],
        [1],
        [0]]),
 array([[0],
        [1],
        [1],
        [0]]),
 array([[0],
        [0],
        [0],
        [0]])]

In [41]:
zeros=np.zeros((10,10))
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [51]:
boolfull=np.full((5,5),True)
boolfull

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [58]:
random=np.random.randn(5,5)
random

array([[-0.54010374,  0.93111456, -0.92911478, -0.67856374, -1.65413141],
       [ 0.02948981,  0.59289515,  1.97377097, -0.14532909,  0.57566387],
       [-0.03916036,  0.11192437, -0.95988705, -0.42326718,  0.76277295],
       [-0.03782202, -1.14622823,  0.78825779, -0.89636198, -0.19731758],
       [ 0.24447337,  1.97706752,  0.06348162,  0.18179309,  0.01167251]])

In [63]:
random.mean()

0.023883617497722366

In [65]:
np.median(random)

0.011672514065200828

In [59]:
random.cumsum()

array([-0.54010374,  0.39101082, -0.53810395, -1.2166677 , -2.87079911,
       -2.84130929, -2.24841414, -0.27464317, -0.41997226,  0.15569161,
        0.11653125,  0.22845562, -0.73143142, -1.1546986 , -0.39192566,
       -0.42974768, -1.57597591, -0.78771812, -1.6840801 , -1.88139768,
       -1.6369243 ,  0.34014322,  0.40362483,  0.58541792,  0.59709044])

In [60]:
random.cumprod()

array([-5.40103736e-01, -5.02898452e-01,  4.67250382e-01, -3.17059168e-01,
        5.24457529e-01,  1.54661544e-02,  9.16980800e-03,  1.80991009e-02,
       -2.63032583e-03, -1.51418354e-03,  5.92959705e-05,  6.63666401e-06,
       -6.37044781e-06,  2.69640148e-06,  2.05674209e-06, -7.77901331e-08,
        8.91652465e-08,  7.02852000e-08, -6.30009811e-08,  1.24312010e-08,
        3.03909765e-09,  6.00850125e-09,  3.81429383e-10,  6.93412258e-11,
        8.09386433e-13])

In [61]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
intersect=np.intersect1d(a,b)
intersect

array([5])

In [62]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
unique=np.unique(names)
unique.sort()
unique

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [67]:
np.ceil(random)

array([[-0.,  1., -0., -0., -1.],
       [ 1.,  1.,  2., -0.,  1.],
       [-0.,  1., -0., -0.,  1.],
       [-0., -1.,  1., -0., -0.],
       [ 1.,  2.,  1.,  1.,  1.]])

In [68]:
np.floor(random)

array([[-1.,  0., -1., -1., -2.],
       [ 0.,  0.,  1., -1.,  0.],
       [-1.,  0., -1., -1.,  0.],
       [-1., -2.,  0., -1., -1.],
       [ 0.,  1.,  0.,  0.,  0.]])

In [73]:
np.where(random>0,1,random)

array([[-0.54010374,  1.        , -0.92911478, -0.67856374, -1.65413141],
       [ 1.        ,  1.        ,  1.        , -0.14532909,  1.        ],
       [-0.03916036,  1.        , -0.95988705, -0.42326718,  1.        ],
       [-0.03782202, -1.14622823,  1.        , -0.89636198, -0.19731758],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ]])

In [74]:
np.percentile(random,(25,50))

array([-0.54010374,  0.01167251])

In [75]:
np.std(random)

0.8552467144191339